// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuuerLZHTksr20dr81vnLdgMvN0tl06Vg',
    appId: '1:368098478624:web:24f9aa3c304400cbfa4a45',
    messagingSenderId: '368098478624',
    projectId: 'wrteam-3c294',
    authDomain: 'wrteam-3c294.firebaseapp.com',
    databaseURL: 'https://wrteam-3c294-default-rtdb.firebaseio.com',
    storageBucket: 'wrteam-3c294.appspot.com',
    measurementId: 'G-SXVVY6125C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6JftC4bxUXX2vHh44ogDkyRRytU8uR0A',
    appId: '1:368098478624:android:166994ab894c6433fa4a45',
    messagingSenderId: '368098478624',
    projectId: 'wrteam-3c294',
    databaseURL: 'https://wrteam-3c294-default-rtdb.firebaseio.com',
    storageBucket: 'wrteam-3c294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZm2hgBV-BmaEWHP6jKWZP57-fHAgO70o',
    appId: '1:368098478624:ios:3846138739cfa8e9fa4a45',
    messagingSenderId: '368098478624',
    projectId: 'wrteam-3c294',
    databaseURL: 'https://wrteam-3c294-default-rtdb.firebaseio.com',
    storageBucket: 'wrteam-3c294.appspot.com',
    iosBundleId: 'com.ebroker.wrteam',
  );
}
